### ISSUE TITLE
regarding rankGPT

### ISSUE THREAD

**Issue by crystalxing06** [sunnweiwei/RankGPT#21]
Hi I have a question regarding the paper, https://aclanthology.org/2023.emnlp-main.923.pdf
For instructional permutation results from chatGPT, have you done experiments to compare with embedding distance based ranking using openAI embeddings? I am curious is permutation zero-shot ranking similar as openAI embedding distance based ranking?or they are quite different. 

Nice paper and thanks for the github contribution.

**Comment by sunnweiwei** [comment]
Hi. Thank you for your interest. I did not compare the OpenAI embeddings. Embedding models are mainly used for the retrieval stage rather than the re-ranking stage, but this paper (https://arxiv.org/pdf/2305.06300.pdf) evaluates the re-ranking performance of OpenAI embedding models on benchmarks, which could be relevant.
